### ISSUE TITLE
Collection::searchable does not exist

### ISSUE THREAD

**Issue by Duohao** [matchish/laravel-scout-elasticsearch#65]
error:
` Method Illuminate\Database\Eloquent\Collection::searchable does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Database\\Eloquent\\Collection::searchable does not exist. at vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:104)`

```
use Laravel\Scout\Searchable;

class Posts extends Model
{
    use Searchable,\Spatie\Tags\HasTags;
```
run command :
```
php artisan scout:import "\codenamepace\Models\Posts"
```

trace:
```
[2019-10-20 18:38:52] local.ERROR: Method Illuminate\Database\Eloquent\Collection::searchable does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Database\\Eloquent\\Collection::searchable does not exist. at vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:104)
[stacktrace]
#0 vendor/matchish/laravel-scout-elasticsearch/src/Jobs/Stages/PullFromSource.php(33): Illuminate\\Support\\Collection->__call('searchable', Array)
#1 vendor/matchish/laravel-scout-elasticsearch/src/Jobs/Import.php(41): Matchish\\ScoutElasticSearch\\Jobs\\Stages\\PullFromSource->handle(Object(Elasticsearch\\Client))
#2 vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(176): Matchish\\ScoutElasticSearch\\Jobs\\Import->Matchish\\ScoutElasticSearch\\Jobs\\{closure}(Object(Matchish\\ScoutElasticSearch\\Jobs\\Stages\\PullFromSource), 2)
#3 vendor/matchish/laravel-scout-elasticsearch/src/Jobs/Import.php(43): Illuminate\\Support\\Collection->each(Object(Closure))
#4 [internal function]: Matchish\\ScoutElasticSearch\\Jobs\\Import->handle(Object(Elasticsearch\\Client))
#5 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#6 vendor/laravel/framework/src/Illuminate/Support/helpers.php(522): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#7 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): value(Object(Closure))
#8 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#9 vendor/laravel/framework/src/Illuminate/Container/Container.php(591): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#10 vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#11 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Matchish\\ScoutElasticSearch\\Jobs\\Import))
#12 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Matchish\\ScoutElasticSearch\\Jobs\\Import))
#13 vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#14 vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(76): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Matchish\\ScoutElasticSearch\\Jobs\\Import))
#15 vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(112): Illuminate\\Bus\\Dispatcher->dispatch(Object(Matchish\\ScoutElasticSearch\\Jobs\\Import))
#16 vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(399): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#17 vendor/laravel/framework/src/Illuminate/Bus/Queueable.php(177): dispatch(Object(Matchish\\ScoutElasticSearch\\Jobs\\Import))
#18 vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(131): Matchish\\ScoutElasticSearch\\Jobs\\QueueableJob->dispatchNextJobInChain()
#19 vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(62): Illuminate\\Queue\\CallQueuedHandler->ensureNextJobInChainIsDispatched(Object(Matchish\\ScoutElasticSearch\\Jobs\\QueueableJob))
#20 vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#21 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(348): Illuminate\\Queue\\Jobs\\Job->fire()
#22 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(294): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#23 vendor/laravel/framework/src/Illuminate/Queue/Worker.php(129): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#24 vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#25 vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#26 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#27 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#28 vendor/laravel/framework/src/Illuminate/Support/helpers.php(522): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#29 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): value(Object(Closure))
#30 vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#31 vendor/laravel/framework/src/Illuminate/Container/Container.php(591): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#32 vendor/laravel/framework/src/Illuminate/Console/Command.php(202): Illuminate\\Container\\Container->call(Array)
#33 vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#34 vendor/laravel/framework/src/Illuminate/Console/Command.php(189): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#35 vendor/symfony/console/Application.php(934): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#36 vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#38 vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#39 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#40 artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#41 {main}
"} 

```

**Comment by strangetin** [comment]
@Duohao Do you happen to use the spiritix/lada-cache package in your project?

**Comment by Duohao** [comment]
@strangetin  no
